import os


configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/demux.smk"
include: "rules/checkpoints.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/qc.smk"


rule all:
    input:
        os.path.join(config["out_dir"], "demultiplexed"),
        expand(
            "{param}/merged/{sample}_bc_001.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/merged/{sample}_cdna_001.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/trimmed/{sample}_bc_trimmed.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/trimmed/{sample}_cdna_trimmed.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            os.path.join(config["out_dir"], "mapped/{sample}_Aligned.sortedByCoord.out.bam"),
            sample=get_sample_ids,
        ),
        expand(
            os.path.join(config["out_dir"], "mapped/{sample}_Solo.out"),
            sample=get_sample_ids,
        ),
        expand(
            os.path.join(config["out_dir"], "mapped/stats/{sample}.stats"),
            sample=get_sample_ids,
        ),
        expand(
            "{param}/qc/fastqc/{sample}_{read_type}.html",
            sample=get_sample_ids,
            param=config["out_dir"],
            read_type=["bc_merged", "cdna_merged", "bc_trimmed", "cdna_trimmed"],
        ),
        expand(
            "{param}/qc/fastqc/{sample}_{read_type}_fastqc.zip",
            sample=get_sample_ids,
            param=config["out_dir"],
            read_type=["bc_merged", "cdna_merged", "bc_trimmed", "cdna_trimmed"],
        ),
        expand(
            "{param}/mapped/stats/{sample}.stats",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        os.path.join(config["out_dir"], "qc/multiqc.html"),
