configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/demux.smk"


sample_ids = sorted(get_sample_ids(config["sample_sheet"]))


rule all:
    input:
        "results/demultiplexed",
        expand("results/merged/{sample}_bc_001.fastq.gz", sample=sample_ids),
        expand("results/merged/{sample}_cdna_001.fastq.gz", sample=sample_ids),
