import os


configfile: "config/config.yaml"


##### load rules #####


include: "rules/common.smk"
include: "rules/demux.smk"
include: "rules/checkpoints.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/mirtop.smk"
include: "rules/qc.smk"


rule all:
    input:
        os.path.join(config["out_dir"], "demuxed"),
        expand(
            "{param}/merged/{sample}_bc_merged.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/merged/{sample}_cdna_merged.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/trimmed/{sample}_bc_trimmed.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/trimmed/{sample}_cdna_trimmed.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/trimmed/{sample}_cutadapt_report.txt",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mapped/{sample}_Aligned.sortedByCoord.out.bam",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mapped/{sample}_Solo.out",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mapped/{sample}_Solo.out/{sample}_{file}",
            sample=get_sample_ids,
            param=config["out_dir"],
            file=[
                "Summary.csv",
                "UMIperCellSorted.txt",
                "Features.stats",
                "Barcodes.stats",
            ],
        ),
        expand(
            "{param}/mapped/{sample}_Log.final.out",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mapped/stats/{sample}.stats",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/collapsed/{sample}_cdna_collapsed.fastq.gz",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        os.path.join(config["out_dir"], "reference/hairpin/index"),
        expand(
            "{param}/mirtop/{sample}_Aligned.sortedByCoord.out.bam",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtop/{sample}_Aligned.sortedByCoord.out.gff",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtop/{sample}_mirtop_stats.log",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtop/{sample}_mirtop_stats.txt",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/qc/fastqc/{sample}_{type}_{suffix}.html",
            sample=get_sample_ids,
            type=["bc", "cdna"],
            suffix=["merged", "trimmed"],
            param=config["out_dir"],
        ),
        expand(
            "{param}/qc/fastqc/{sample}_{type}_{suffix}_fastqc.zip",
            sample=get_sample_ids,
            type=["bc", "cdna"],
            suffix=["merged", "trimmed"],
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtrace/{sample}",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtop/{sample}_CB_Solo.out/{features}/CellReads.stats",
            sample=get_sample_ids,
            param=config["out_dir"],
            features=config["star"]["features"],
        ),
        expand(
            "{param}/mirtop/split/{sample}",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        expand(
            "{param}/mirtop/{sample}_mirtop_counts_matrix.tsv",
            sample=get_sample_ids,
            param=config["out_dir"],
        ),
        os.path.join(config["out_dir"], "qc/multiqc_report.html"),
