report_section_order:
  software_versions:
    order: -1000
  parts-seq-summary:
    order: -1001

export_plots: true

top_modules:
  - 'star'
  - 'custom_content'

custom_data:
  starsolo_summary:
    id: 'starsolo_summary'
    parent_id: 'custom_content'
    parent_name: 'STARsolo'
    file_format: 'csv'
    plot_type: 'table'

  starsolo_umi:
    id: 'starsolo_umi'
    parent_id: 'custom_content'
    parent_name: 'STARsolo'
    file_format: 'tsv'
    plot_type: 'linegraph'
    pconfig:
      title: 'Barcode rank plot'
      ylab: 'UMI counts'
      xlab: 'Cell Barcodes'
      ylog: true
      xlog: true

  starsolo_barcode:
    id: 'starsolo_barcode'
    parent_id: 'custom_content'
    parent_name: 'STARsolo'
    file_format: 'tsv'
    plot_type: 'bargraph'
    pconfig:
      title: 'Barcode Stats'
      xlab: '# Reads'

  starsolo_feature:
    id: 'starsolo_feature'
    parent_id: 'custom_content'
    parent_name: 'STARsolo'
    file_format: 'tsv'
    plot_type: 'bargraph'
    pconfig:
      title: 'Feature Stats'
      xlab: '# Reads'

fn_clean_sample_names:
  - type: 'regex_keep'
    pattern: '_Solo.out'
    replacement: ''

sp:
  starsolo_summary:
    fn: '*_Solo.out/GeneFull/*_Summary.csv'
  starsolo_umi:
    fn: '*_Solo.out/GeneFull/*_UMIperCellSorted.txt'
  starsolo_barcode:
    fn: '*_Solo.out/*_Barcodes.stats'
  starsolo_feature:
    fn: '*_Solo.out/GeneFull/*_Features.stats'
