report_section_order:
    software_versions:
        order: -1000
    parts-seq-summary:
        order: -1001

export_plots: true

top_modules:
  - 'star'
  - 'starsolo'

# --------------------------------
# custom data
# --------------------------------

custom_data:
  starsolo_summary:
    parent_id: 'custom_content'
    parent_name: 'STARsolo Summary'
    file_format: 'csv'
    plot_type: 'table'

  starsolo_umi:
    parent_id: 'custom_content'
    parent_name: 'STARsolo UMI Rank'
    file_format: 'tsv'
    plot_type: 'linegraph'
    pconfig:
      title: 'Barcode rank plot'
      ylab: 'UMI counts'
      xlab: 'Cell Barcodes'
      yLog: True
      xLog: True

  starsolo_barcode:
    parent_id: 'custom_content'
    parent_name: 'STARsolo Barcode Stats'
    file_format: 'tsv'
    plot_type: 'bargraph'
    pconfig:
      title: 'Barcode Stats'
      xlab: '# Reads'

  starsolo_feature:
    parent_id: 'custom_content'
    parent_name: 'STARsolo Feature Stats'
    file_format: 'tsv'
    plot_type: 'bargraph'
    pconfig:
      title: 'Feature Stats'
      xlab: '# Reads'

sp:
    starsolo_summary:
        fn: '*_Summary.csv'
    starsolo_umi:
        fn: '*_UMIperCellSorted.txt'
    starsolo_barcode:
        fn: '*_Barcodes.stats'
    starsolo_feature:
        fn: '*_Features.stats'
    
extra_fn_clean_exts:
    - type: 'replace'
      pattern: '_Summary.csv'
    - type: 'replace'
      pattern: '_UMIperCellSorted.txt'
    - type: 'replace'
      pattern: '_Barcodes.stats'
    - type: 'replace'
      pattern: '_Features.stats'
    - type: 'regex'
      pattern: '(_trimmed)'
      replacement: '\1'
