report_section_order:
    software_versions:
        order: -1000
    solo-in-drops-summary:
        order: -1001

export_plots: true

top_modules:
  - 'star'
  - 'starsolo'

# --------------------------------
# custom data
# --------------------------------

custom_data:
    starsolo_summary:
        parent_id: 'mapped'
        parent_name: 'STARsolo' 
        file_format: 'csv'
        plot_type: 'table'
    starsolo_umi:
        parent_id: 'mapped'
        parent_name: 'STARsolo' 
        file_format: 'tsv'
        plot_type: 'linegraph'
        pconfig:
            id: 'starsolo_umi'
            title: 'Barcode rank plot'
            ylab: 'UMI counts'
            xlab: 'Cell Barcodes'
            yLog: True
            xLog: True
    starsolo_barcode:
        parent_id: 'mapped'
        parent_name: 'STARsolo' 
        file_format: 'tsv'
        plot_type: 'bargraph'
        pconfig:
            id: 'starsolo_barcode'
            title: 'Barcode Stats'
            xlab: '# Reads'
    starsolo_feature:
        parent_id: 'mapped'
        parent_name: 'STARsolo' 
        file_format: 'tsv'
        plot_type: 'bargraph'
        pconfig:
            id: 'starsolo_feature'
            title: 'Feature Stats'
            xlab: '# Reads'

sp:
    starsolo_summary:
        fn: '*_Summary.csv'
    starsolo_umi:
        fn: '*_UMIperCellSorted.txt'
    starsolo_barcode:
        fn: '*_Barcodes.stats'
    starsolo_feature:
        fn: '*_Features.stats'
    
extra_fn_clean_exts:
    - type: 'replace'
      pattern: '_Summary.csv'
    - type: 'replace'
      pattern: '_UMIperCellSorted.txt'
    - type: 'replace'
      pattern: '_Barcodes.stats'
    - type: 'replace'
      pattern: '_Features.stats'